#pragma once

using namespace ATL;

template <class T>
class CProxy_ICodeCoverageEvents : public IConnectionPointImpl<T, &__uuidof( _ICodeCoverageEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
