// OpenCoverProfiler.idl : IDL source for OpenCover.Profiler
//

// This file will be processed by the MIDL tool to
// produce the type library (OpenCoverProfiler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(72FFC626-5A74-4821-B246-BCAB0A58A13E),
	pointer_default(unique)
]
interface ICodeCoverage : IUnknown{
};
[
	uuid(437C5B7B-DA44-4DE8-8629-CC994EA549EC),
	version(1.0),
]
library OpenCoverProfilerLib
{
	importlib("stdole2.tlb");
	[
		uuid(5BC0E58A-DFAB-4746-B318-BDF8BE5F452F)		
	]
	dispinterface _ICodeCoverageEvents
	{
		properties:
		methods:
	};
	[
		uuid(1542C21D-80C3-45E6-A56C-A9C1E4BEB7B8)		
	]
	coclass CodeCoverage
	{
		[default] interface ICodeCoverage;
		[default, source] dispinterface _ICodeCoverageEvents;
	};
};

