// OpenCoverProfiler.idl : IDL source for OpenCover.Profiler
//

// This file will be processed by the MIDL tool to
// produce the type library (OpenCoverProfiler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "corprof.idl";

[
	uuid(9F34E05F-9627-4477-A016-0D56DEF7A38E),
	version(1.0),
]
library OpenCoverProfilerLib
{
	importlib("stdole2.tlb");
	[
		uuid(A7A1EDD8-D9A9-4D51-85EA-514A8C4A9100)
	]
	coclass CodeCoverage
	{
		[default] interface ICorProfilerCallback;
		interface ICorProfilerCallback2;
		interface ICorProfilerCallback3;
	};
};
