// OpenCoverProfiler.idl : IDL source for OpenCover.Profiler
//

// This file will be processed by the MIDL tool to
// produce the type library (OpenCoverProfiler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "corprof.idl";

[
	uuid(437C5B7B-DA44-4DE8-8629-CC994EA549EC),
	version(1.0),
]
library OpenCoverProfilerLib
{
	importlib("stdole2.tlb");
	[
		uuid(1542C21D-80C3-45E6-A56C-A9C1E4BEB7B8)
	]
	coclass CodeCoverage
	{
		[default] interface ICorProfilerCallback;
		interface ICorProfilerCallback2;
		interface ICorProfilerCallback3;
		interface ICorProfilerCallback4;
		interface ICorProfilerCallback5;
        interface ICorProfilerCallback6;
		interface ICorProfilerCallback7;
		interface ICorProfilerCallback8;
	};
};
