
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _Start;
//     struct _StartResponse;
//     struct _Stop;
//     struct _StopResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

typedef struct _Start _Start;

// typeDescription: n/a
typedef struct _StartResponse 
{
    BOOL StartResult;
} _StartResponse;

typedef struct _Stop _Stop;

// typeDescription: n/a
typedef struct _StopResponse 
{
    BOOL StopResult;
} _StopResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _opencover_profiler_xsd
{
    struct // globalElements
    {
        // xml element: Start ("urn:opencover.profiler")
        // c type: _Start
        // elementDescription: opencover_profiler_xsd.globalElements.Start
        WS_ELEMENT_DESCRIPTION Start;
        
        // xml element: StartResponse ("urn:opencover.profiler")
        // c type: _StartResponse
        // elementDescription: opencover_profiler_xsd.globalElements.StartResponse
        WS_ELEMENT_DESCRIPTION StartResponse;
        
        // xml element: Stop ("urn:opencover.profiler")
        // c type: _Stop
        // elementDescription: opencover_profiler_xsd.globalElements.Stop
        WS_ELEMENT_DESCRIPTION Stop;
        
        // xml element: StopResponse ("urn:opencover.profiler")
        // c type: _StopResponse
        // elementDescription: opencover_profiler_xsd.globalElements.StopResponse
        WS_ELEMENT_DESCRIPTION StopResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION Start;
        WS_STRUCT_DESCRIPTION StartResponse;
        WS_STRUCT_DESCRIPTION Stop;
        WS_STRUCT_DESCRIPTION StopResponse;
    } externallyReferencedTypes;
} _opencover_profiler_xsd;

extern const _opencover_profiler_xsd opencover_profiler_xsd;

#ifdef __cplusplus
}
#endif

