
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct ArrayOfInstrumentPoint;
//     struct InstrumentPoint;
//     struct _Started;
//     struct _StartedResponse;
//     struct _Stopping;
//     struct _StoppingResponse;
//     struct _TrackAssembly;
//     struct _TrackAssemblyResponse;
//     struct _GetSequencePoints;
//     struct _GetSequencePointsResponse;
//     struct ArrayOfInstrumentPoint;
//     struct InstrumentPoint;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: opencover_profiler_xsd.globalTypes.ArrayOfInstrumentPoint
typedef struct ArrayOfInstrumentPoint 
{
    unsigned int InstrumentPointCount;
    __field_ecount(InstrumentPointCount)struct InstrumentPoint** InstrumentPoint; // optional
} ArrayOfInstrumentPoint;

// typeDescription: opencover_profiler_xsd.globalTypes.InstrumentPoint
typedef struct InstrumentPoint 
{
    int Offset;
    int Ordinal;
    __int64 UniqueId;
} InstrumentPoint;

typedef struct _Started _Started;

typedef struct _StartedResponse _StartedResponse;

typedef struct _Stopping _Stopping;

typedef struct _StoppingResponse _StoppingResponse;

// typeDescription: n/a
typedef struct _TrackAssembly 
{
    WCHAR* moduleName; // optional
    WCHAR* assemblyName; // optional
} _TrackAssembly;

// typeDescription: n/a
typedef struct _TrackAssemblyResponse 
{
    BOOL TrackAssemblyResult;
} _TrackAssemblyResponse;

// typeDescription: n/a
typedef struct _GetSequencePoints 
{
    WCHAR* moduleName; // optional
    int functionToken;
} _GetSequencePoints;

// typeDescription: n/a
typedef struct _GetSequencePointsResponse 
{
    BOOL GetSequencePointsResult;
    unsigned int sequencePointsCount;
    __field_ecount_opt(sequencePointsCount)struct InstrumentPoint** sequencePoints; // optional
} _GetSequencePointsResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _opencover_profiler_xsd
{
    struct // globalTypes
    {
        // xml type: ArrayOfInstrumentPoint ("urn:opencover.profiler")
        // c type: ArrayOfInstrumentPoint
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: opencover_profiler_xsd.globalTypes.ArrayOfInstrumentPoint
        WS_STRUCT_DESCRIPTION ArrayOfInstrumentPoint;
        
        // xml type: InstrumentPoint ("urn:opencover.profiler")
        // c type: InstrumentPoint
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: opencover_profiler_xsd.globalTypes.InstrumentPoint
        WS_STRUCT_DESCRIPTION InstrumentPoint;
        
    } globalTypes;
    struct // globalElements
    {
        // xml element: Started ("urn:opencover.profiler")
        // c type: _Started
        // elementDescription: opencover_profiler_xsd.globalElements.Started
        WS_ELEMENT_DESCRIPTION Started;
        
        // xml element: StartedResponse ("urn:opencover.profiler")
        // c type: _StartedResponse
        // elementDescription: opencover_profiler_xsd.globalElements.StartedResponse
        WS_ELEMENT_DESCRIPTION StartedResponse;
        
        // xml element: Stopping ("urn:opencover.profiler")
        // c type: _Stopping
        // elementDescription: opencover_profiler_xsd.globalElements.Stopping
        WS_ELEMENT_DESCRIPTION Stopping;
        
        // xml element: StoppingResponse ("urn:opencover.profiler")
        // c type: _StoppingResponse
        // elementDescription: opencover_profiler_xsd.globalElements.StoppingResponse
        WS_ELEMENT_DESCRIPTION StoppingResponse;
        
        // xml element: TrackAssembly ("urn:opencover.profiler")
        // c type: _TrackAssembly
        // elementDescription: opencover_profiler_xsd.globalElements.TrackAssembly
        WS_ELEMENT_DESCRIPTION TrackAssembly;
        
        // xml element: TrackAssemblyResponse ("urn:opencover.profiler")
        // c type: _TrackAssemblyResponse
        // elementDescription: opencover_profiler_xsd.globalElements.TrackAssemblyResponse
        WS_ELEMENT_DESCRIPTION TrackAssemblyResponse;
        
        // xml element: GetSequencePoints ("urn:opencover.profiler")
        // c type: _GetSequencePoints
        // elementDescription: opencover_profiler_xsd.globalElements.GetSequencePoints
        WS_ELEMENT_DESCRIPTION GetSequencePoints;
        
        // xml element: GetSequencePointsResponse ("urn:opencover.profiler")
        // c type: _GetSequencePointsResponse
        // elementDescription: opencover_profiler_xsd.globalElements.GetSequencePointsResponse
        WS_ELEMENT_DESCRIPTION GetSequencePointsResponse;
        
        // xml element: ArrayOfInstrumentPoint ("urn:opencover.profiler")
        // c type: ArrayOfInstrumentPoint
        // elementDescription: opencover_profiler_xsd.globalElements.ArrayOfInstrumentPoint
        WS_ELEMENT_DESCRIPTION ArrayOfInstrumentPoint;
        
        // xml element: InstrumentPoint ("urn:opencover.profiler")
        // c type: InstrumentPoint
        // elementDescription: opencover_profiler_xsd.globalElements.InstrumentPoint
        WS_ELEMENT_DESCRIPTION InstrumentPoint;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION Started;
        WS_STRUCT_DESCRIPTION StartedResponse;
        WS_STRUCT_DESCRIPTION Stopping;
        WS_STRUCT_DESCRIPTION StoppingResponse;
        WS_STRUCT_DESCRIPTION TrackAssembly;
        WS_STRUCT_DESCRIPTION TrackAssemblyResponse;
        WS_STRUCT_DESCRIPTION GetSequencePoints;
        WS_STRUCT_DESCRIPTION GetSequencePointsResponse;
    } externallyReferencedTypes;
} _opencover_profiler_xsd;

extern const _opencover_profiler_xsd opencover_profiler_xsd;

#ifdef __cplusplus
}
#endif

