
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "opencover.profiler.xsd.h"

typedef struct _opencover_profiler_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _StartResponse
        {
            WS_FIELD_DESCRIPTION StartResult;
            WS_FIELD_DESCRIPTION* _StartResponseFields [1]; 
        } _StartResponsedescs; // end of _StartResponse
        struct // _StopResponse
        {
            WS_FIELD_DESCRIPTION StopResult;
            WS_FIELD_DESCRIPTION* _StopResponseFields [1]; 
        } _StopResponsedescs; // end of _StopResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _StartTypeName;  // Start
            WS_XML_STRING _StartTypeNamespace;  // urn:opencover.profiler
            WS_XML_STRING _StartResponseTypeName;  // StartResponse
            WS_XML_STRING _StartResponseStartResultLocalName;  // StartResult
            WS_XML_STRING _StopTypeName;  // Stop
            WS_XML_STRING _StopResponseTypeName;  // StopResponse
            WS_XML_STRING _StopResponseStopResultLocalName;  // StopResult
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _opencover_profiler_xsdLocalDefinitions;

const static _opencover_profiler_xsdLocalDefinitions opencover_profiler_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _StartResponse
            { // field description for StartResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartResponseStartResultLocalName, // StartResult
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_StartResponse, StartResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for StartResult
            {    // fields description for _StartResponse
            (WS_FIELD_DESCRIPTION*)&opencover_profiler_xsdLocalDefinitions.globalElements._StartResponsedescs.StartResult,
            },
        },    // _StartResponse
        {   // _StopResponse
            { // field description for StopResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopResponseStopResultLocalName, // StopResult
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_StopResponse, StopResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for StopResult
            {    // fields description for _StopResponse
            (WS_FIELD_DESCRIPTION*)&opencover_profiler_xsdLocalDefinitions.globalElements._StopResponsedescs.StopResult,
            },
        },    // _StopResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Start",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("urn:opencover.profiler",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("StartResponse",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("StartResult",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("Stop",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("StopResponse",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("StopResult",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 6),
        },  // end of xmlStrings
        
        {   // opencover_profiler_xsddictionary
        // 785543a9-aa19-4a3d-86b5-3bc38d4d43f2 
        { 0x785543a9, 0xaa19, 0x4a3d, { 0x86, 0xb5, 0x3b,0xc3, 0x8d, 0x4d, 0x43, 0xf2 } },
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings,
        7,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of opencover_profiler_xsdLocalDefinitions

const _opencover_profiler_xsd opencover_profiler_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeName, // Start
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.Start,
        },
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartResponseTypeName, // StartResponse
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.StartResponse,
        },
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopTypeName, // Stop
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.Stop,
        },
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopResponseTypeName, // StopResponse
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.StopResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeName, // Start
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _Start
        {
        sizeof(_StartResponse),
        __alignof(_StartResponse),
        (WS_FIELD_DESCRIPTION**)&opencover_profiler_xsdLocalDefinitions.globalElements._StartResponsedescs._StartResponseFields,
        WsCountOf(opencover_profiler_xsdLocalDefinitions.globalElements._StartResponsedescs._StartResponseFields),
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartResponseTypeName, // StartResponse
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _StartResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopTypeName, // Stop
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _Stop
        {
        sizeof(_StopResponse),
        __alignof(_StopResponse),
        (WS_FIELD_DESCRIPTION**)&opencover_profiler_xsdLocalDefinitions.globalElements._StopResponsedescs._StopResponseFields,
        WsCountOf(opencover_profiler_xsdLocalDefinitions.globalElements._StopResponsedescs._StopResponseFields),
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopResponseTypeName, // StopResponse
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _StopResponse
    }, // end of externallyReferencedTypes;
}; // end of _opencover_profiler_xsd
