
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     enum VisitType;
//     enum VisitType;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: OpenCover_Framework_Common_xsd.globalTypes.VisitType
typedef enum VisitType
{
    VisitTypeSequencePoint = 0,
} VisitType;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _OpenCover_Framework_Common_xsd
{
    struct // globalTypes
    {
        // xml type: VisitType ("http://schemas.datacontract.org/2004/07/OpenCover.Framework.Common")
        // c type: VisitType
        // WS_TYPE: WS_ENUM_TYPE
        // typeDescription: OpenCover_Framework_Common_xsd.globalTypes.VisitType
        WS_ENUM_DESCRIPTION VisitType;
        
    } globalTypes;
    struct // globalElements
    {
        // xml element: VisitType ("http://schemas.datacontract.org/2004/07/OpenCover.Framework.Common")
        // c type: VisitType
        // elementDescription: OpenCover_Framework_Common_xsd.globalElements.VisitType
        WS_ELEMENT_DESCRIPTION VisitType;
        
    } globalElements;
} _OpenCover_Framework_Common_xsd;

extern const _OpenCover_Framework_Common_xsd OpenCover_Framework_Common_xsd;

#ifdef __cplusplus
}
#endif

