
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "opencover.profiler.xsd.h"

typedef struct _opencover_profiler_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _StartTypeName;  // Start
            WS_XML_STRING _StartTypeNamespace;  // urn:opencover.profiler
            WS_XML_STRING _StartResponseTypeName;  // StartResponse
            WS_XML_STRING _StopTypeName;  // Stop
            WS_XML_STRING _StopResponseTypeName;  // StopResponse
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _opencover_profiler_xsdLocalDefinitions;

const static _opencover_profiler_xsdLocalDefinitions opencover_profiler_xsdLocalDefinitions =
{
    {  // global elements
        0,
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Start",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("urn:opencover.profiler",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("StartResponse",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Stop",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("StopResponse",&opencover_profiler_xsdLocalDefinitions.dictionary.dict, 4),
        },  // end of xmlStrings
        
        {   // opencover_profiler_xsddictionary
        // 9186bca8-88e2-42e2-855e-a4fa10976689 
        { 0x9186bca8, 0x88e2, 0x42e2, { 0x85, 0x5e, 0xa4,0xfa, 0x10, 0x97, 0x66, 0x89 } },
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings,
        5,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of opencover_profiler_xsdLocalDefinitions

const _opencover_profiler_xsd opencover_profiler_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeName, // Start
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.Start,
        },
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartResponseTypeName, // StartResponse
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.StartResponse,
        },
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopTypeName, // Stop
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.Stop,
        },
        {
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopResponseTypeName, // StopResponse
            (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
            WS_STRUCT_TYPE,
            (void*)&opencover_profiler_xsd.externallyReferencedTypes.StopResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeName, // Start
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _Start
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartResponseTypeName, // StartResponse
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _StartResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopTypeName, // Stop
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _Stop
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StopResponseTypeName, // StopResponse
        (WS_XML_STRING*)&opencover_profiler_xsdLocalDefinitions.dictionary.xmlStrings._StartTypeNamespace, // urn:opencover.profiler
        0,
        0,
        0,
        },   // end of struct description for _StopResponse
    }, // end of externallyReferencedTypes;
}; // end of _opencover_profiler_xsd
