
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "OpenCover.Framework.Common.xsd.h"

typedef struct _OpenCover_Framework_Common_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct {  //  VisitType
            WS_ENUM_VALUE VisitTypeValues[1];
            unsigned long nameIndices[1];
        } VisitTypeenumDesc; // end of VisitType
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING VisitTypeSequencePoint;  // SequencePoint
            WS_XML_STRING VisitTypeTypeName;  // VisitType
            WS_XML_STRING VisitTypeTypeNamespace;  // http://schemas.datacontract.org/2004/07/OpenCover.Framework.Common
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _OpenCover_Framework_Common_xsdLocalDefinitions;

const static _OpenCover_Framework_Common_xsdLocalDefinitions OpenCover_Framework_Common_xsdLocalDefinitions =
{
    { // global types
        0,
        { // VisitType
            { //  WS_ENUM_VALUE
                {
                0, 
                (WS_XML_STRING*)&OpenCover_Framework_Common_xsdLocalDefinitions.dictionary.xmlStrings.VisitTypeSequencePoint, // SequencePoint
                },
            }, //  WS_ENUM_VALUE
            {  0,},  // nameIndices
        }, //VisitType
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("SequencePoint",&OpenCover_Framework_Common_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("VisitType",&OpenCover_Framework_Common_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/OpenCover.Framework.Common",&OpenCover_Framework_Common_xsdLocalDefinitions.dictionary.dict, 2),
        },  // end of xmlStrings
        
        {   // OpenCover_Framework_Common_xsddictionary
        // ec29cb86-da7b-4825-a531-934d695be91b 
        { 0xec29cb86, 0xda7b, 0x4825, { 0xa5, 0x31, 0x93,0x4d, 0x69, 0x5b, 0xe9, 0x1b } },
        (WS_XML_STRING*)&OpenCover_Framework_Common_xsdLocalDefinitions.dictionary.xmlStrings,
        3,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of OpenCover_Framework_Common_xsdLocalDefinitions

const _OpenCover_Framework_Common_xsd OpenCover_Framework_Common_xsd =
{
    {// globalTypes
        { //  VisitType
            (WS_ENUM_VALUE *)&OpenCover_Framework_Common_xsdLocalDefinitions.globalTypes.VisitTypeenumDesc.VisitTypeValues,
            1,
            13,
            (unsigned long *)&OpenCover_Framework_Common_xsdLocalDefinitions.globalTypes.VisitTypeenumDesc.nameIndices,
        }, //  end of VisitType
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&OpenCover_Framework_Common_xsdLocalDefinitions.dictionary.xmlStrings.VisitTypeTypeName, // VisitType
            (WS_XML_STRING*)&OpenCover_Framework_Common_xsdLocalDefinitions.dictionary.xmlStrings.VisitTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/OpenCover.Framework.Common
            WS_ENUM_TYPE,
            (WS_ENUM_DESCRIPTION*)&OpenCover_Framework_Common_xsd.globalTypes.VisitType,
        },
    }, // globalElements
}; // end of _OpenCover_Framework_Common_xsd
