
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schemas.microsoft.com.2003.10.Serialization.xsd.h"

typedef struct _schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions 
{
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING FactoryTypeTypeName;  // FactoryType
            WS_XML_STRING FactoryTypeTypeNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_STRING IdTypeName;  // Id
            WS_XML_STRING RefTypeName;  // Ref
            WS_XML_STRING anyTypeTypeName;  // anyType
            WS_XML_STRING anyURITypeName;  // anyURI
            WS_XML_STRING base64BinaryTypeName;  // base64Binary
            WS_XML_STRING BooleanTypeName;  // boolean
            WS_XML_STRING ByteTypeName;  // byte
            WS_XML_STRING dateTimeTypeName;  // dateTime
            WS_XML_STRING DecimalTypeName;  // decimal
            WS_XML_STRING DoubleTypeName;  // double
            WS_XML_STRING FloatTypeName;  // float
            WS_XML_STRING IntTypeName;  // int
            WS_XML_STRING LongTypeName;  // long
            WS_XML_STRING QNameTypeName;  // QName
            WS_XML_STRING ShortTypeName;  // short
            WS_XML_STRING StringTypeName;  // string
            WS_XML_STRING unsignedByteTypeName;  // unsignedByte
            WS_XML_STRING unsignedIntTypeName;  // unsignedInt
            WS_XML_STRING unsignedLongTypeName;  // unsignedLong
            WS_XML_STRING unsignedShortTypeName;  // unsignedShort
            WS_XML_STRING CharTypeName;  // char
            WS_XML_STRING durationTypeName;  // duration
            WS_XML_STRING guidTypeName;  // guid
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions;

const static _schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions =
{
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("FactoryType",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("Id",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Ref",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("anyType",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("anyURI",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("base64Binary",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("boolean",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("byte",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("dateTime",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("decimal",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("double",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("float",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("int",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("long",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("QName",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("short",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("string",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedByte",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedInt",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedLong",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedShort",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("char",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("duration",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("guid",&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.dict, 24),
        },  // end of xmlStrings
        
        {   // schemas_microsoft_com_2003_10_Serialization_xsddictionary
        // 1a57305d-eb8e-4d27-ac6c-f6a84828fb0f 
        { 0x1a57305d, 0xeb8e, 0x4d27, { 0xac, 0x6c, 0xf6,0xa8, 0x48, 0x28, 0xfb, 0x0f } },
        (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings,
        25,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions

const _schemas_microsoft_com_2003_10_Serialization_xsd schemas_microsoft_com_2003_10_Serialization_xsd =
{
    {// globalAttributes
        { //  FactoryType
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeName, // FactoryType
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_QNAME_TYPE,
        }, //  end of FactoryType
        { //  Id
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.IdTypeName, // Id
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_WSZ_TYPE,
        }, //  end of Id
        { //  Ref
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.RefTypeName, // Ref
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_WSZ_TYPE,
        }, //  end of Ref
    }, // globalAttributes
    {// globalElements
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.anyTypeTypeName, // anyType
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_BUFFER_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.anyURITypeName, // anyURI
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_WSZ_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.base64BinaryTypeName, // base64Binary
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_BYTES_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.BooleanTypeName, // boolean
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_BOOL_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.ByteTypeName, // byte
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT8_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.dateTimeTypeName, // dateTime
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DATETIME_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.DecimalTypeName, // decimal
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DECIMAL_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.DoubleTypeName, // double
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DOUBLE_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FloatTypeName, // float
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_FLOAT_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.IntTypeName, // int
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT32_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.LongTypeName, // long
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT64_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.QNameTypeName, // QName
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_QNAME_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.ShortTypeName, // short
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT16_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.StringTypeName, // string
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_WSZ_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.unsignedByteTypeName, // unsignedByte
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT8_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.unsignedIntTypeName, // unsignedInt
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT32_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.unsignedLongTypeName, // unsignedLong
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT64_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.unsignedShortTypeName, // unsignedShort
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT16_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.CharTypeName, // char
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT32_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.durationTypeName, // duration
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DURATION_TYPE,
        },
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.guidTypeName, // guid
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_GUID_TYPE,
        },
    }, // globalElements
}; // end of _schemas_microsoft_com_2003_10_Serialization_xsd
