
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:


// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _schemas_microsoft_com_2003_10_Serialization_xsd
{
    struct // globalAttributes
    {
        // xml attribute: FactoryType ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WS_XML_QNAME
        // attributeDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalAttributes.FactoryType
        WS_ATTRIBUTE_DESCRIPTION FactoryType;
        
        // xml attribute: Id ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WCHAR*
        // attributeDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalAttributes.Id
        WS_ATTRIBUTE_DESCRIPTION Id;
        
        // xml attribute: Ref ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WCHAR*
        // attributeDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalAttributes.Ref
        WS_ATTRIBUTE_DESCRIPTION Ref;
        
    } globalAttributes;
    struct // globalElements
    {
        // xml element: anyType ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WS_XML_BUFFER*
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.anyType
        WS_ELEMENT_DESCRIPTION anyType;
        
        // xml element: anyURI ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WCHAR*
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.anyURI
        WS_ELEMENT_DESCRIPTION anyURI;
        
        // xml element: base64Binary ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WS_BYTES
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.base64Binary
        WS_ELEMENT_DESCRIPTION base64Binary;
        
        // xml element: boolean ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: BOOL
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Boolean
        WS_ELEMENT_DESCRIPTION Boolean;
        
        // xml element: byte ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: char
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Byte
        WS_ELEMENT_DESCRIPTION Byte;
        
        // xml element: dateTime ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WS_DATETIME
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.dateTime
        WS_ELEMENT_DESCRIPTION dateTime;
        
        // xml element: decimal ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: DECIMAL
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Decimal
        WS_ELEMENT_DESCRIPTION Decimal;
        
        // xml element: double ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: double
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Double
        WS_ELEMENT_DESCRIPTION Double;
        
        // xml element: float ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: float
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Float
        WS_ELEMENT_DESCRIPTION Float;
        
        // xml element: int ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: int
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Int
        WS_ELEMENT_DESCRIPTION Int;
        
        // xml element: long ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: __int64
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Long
        WS_ELEMENT_DESCRIPTION Long;
        
        // xml element: QName ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WS_XML_QNAME
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.QName
        WS_ELEMENT_DESCRIPTION QName;
        
        // xml element: short ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: short
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Short
        WS_ELEMENT_DESCRIPTION Short;
        
        // xml element: string ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WCHAR*
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.String
        WS_ELEMENT_DESCRIPTION String;
        
        // xml element: unsignedByte ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: unsigned char
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.unsignedByte
        WS_ELEMENT_DESCRIPTION unsignedByte;
        
        // xml element: unsignedInt ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: unsigned int
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.unsignedInt
        WS_ELEMENT_DESCRIPTION unsignedInt;
        
        // xml element: unsignedLong ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: unsigned __int64
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.unsignedLong
        WS_ELEMENT_DESCRIPTION unsignedLong;
        
        // xml element: unsignedShort ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: unsigned short
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.unsignedShort
        WS_ELEMENT_DESCRIPTION unsignedShort;
        
        // xml element: char ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: int
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.Char
        WS_ELEMENT_DESCRIPTION Char;
        
        // xml element: duration ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: WS_DURATION
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.duration
        WS_ELEMENT_DESCRIPTION duration;
        
        // xml element: guid ("http://schemas.microsoft.com/2003/10/Serialization/")
        // c type: GUID
        // elementDescription: schemas_microsoft_com_2003_10_Serialization_xsd.globalElements.guid
        WS_ELEMENT_DESCRIPTION guid;
        
    } globalElements;
} _schemas_microsoft_com_2003_10_Serialization_xsd;

extern const _schemas_microsoft_com_2003_10_Serialization_xsd schemas_microsoft_com_2003_10_Serialization_xsd;

#ifdef __cplusplus
}
#endif

