
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "opencover.profiler.xsd.h"
#include "opencover.profiler.wsdl.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct // contracts
    {
        struct // NetTcpBinding_IProfilerCommunication
        {
            struct // NetTcpBinding_IProfilerCommunication_Started
            {
                WS_OPERATION_DESCRIPTION NetTcpBinding_IProfilerCommunication_Started;
            } NetTcpBinding_IProfilerCommunication_Started;
            struct // NetTcpBinding_IProfilerCommunication_TrackAssembly
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION NetTcpBinding_IProfilerCommunication_TrackAssembly;
            } NetTcpBinding_IProfilerCommunication_TrackAssembly;
            struct // NetTcpBinding_IProfilerCommunication_Stopping
            {
                WS_OPERATION_DESCRIPTION NetTcpBinding_IProfilerCommunication_Stopping;
            } NetTcpBinding_IProfilerCommunication_Stopping;
            WS_OPERATION_DESCRIPTION* operations[3];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } NetTcpBinding_IProfilerCommunication;
    } contracts;  // endof contracts 
    struct // policies
    {
        struct // NetTcpBinding_IProfilerCommunication
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } NetTcpBinding_IProfilerCommunication;
    } policies;
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING NetTcpBinding_IProfilerCommunicationendpointReferenceString;  // <wsa10:EndpointReference xmlns:wsa10="http://www.w3.org/2005/08/addressing">...
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK NetTcpBinding_IProfilerCommunication_StartedOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    NetTcpBinding_IProfilerCommunication_StartedCallback _operation = (NetTcpBinding_IProfilerCommunication_StartedCallback)_callback;
    _stackStruct;
    return _operation( 
        _context,
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct NetTcpBinding_IProfilerCommunication_TrackAssemblyParamStruct 
{
    WCHAR** moduleName;
    WCHAR** assemblyName;
    BOOL* TrackAssemblyResult;
} NetTcpBinding_IProfilerCommunication_TrackAssemblyParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK NetTcpBinding_IProfilerCommunication_TrackAssemblyOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    NetTcpBinding_IProfilerCommunication_TrackAssemblyCallback _operation = (NetTcpBinding_IProfilerCommunication_TrackAssemblyCallback)_callback;
    NetTcpBinding_IProfilerCommunication_TrackAssemblyParamStruct *_stack =(NetTcpBinding_IProfilerCommunication_TrackAssemblyParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->moduleName),
        *(_stack->assemblyName),
        (_stack->TrackAssemblyResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK NetTcpBinding_IProfilerCommunication_StoppingOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    NetTcpBinding_IProfilerCommunication_StoppingCallback _operation = (NetTcpBinding_IProfilerCommunication_StoppingCallback)_callback;
    _stackStruct;
    return _operation( 
        _context,
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    { // contracts
        {    // NetTcpBinding_IProfilerCommunication,
            { // NetTcpBinding_IProfilerCommunication_Started
                {    // operation description for NetTcpBinding_IProfilerCommunication_Started
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&opencover_profiler_wsdl.messages.IProfilerCommunication_Started_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&opencover_profiler_wsdl.messages.IProfilerCommunication_Started_OutputMessage, 
                    0,
                    0,
                    0,
                    0,
                    NetTcpBinding_IProfilerCommunication_StartedOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for NetTcpBinding_IProfilerCommunication_Started
            },  // NetTcpBinding_IProfilerCommunication_Started
            { // NetTcpBinding_IProfilerCommunication_TrackAssembly
                { // parameter descriptions for NetTcpBinding_IProfilerCommunication_TrackAssembly
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0 },
                },    // parameter descriptions for NetTcpBinding_IProfilerCommunication_TrackAssembly
                {    // operation description for NetTcpBinding_IProfilerCommunication_TrackAssembly
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&opencover_profiler_wsdl.messages.IProfilerCommunication_TrackAssembly_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&opencover_profiler_wsdl.messages.IProfilerCommunication_TrackAssembly_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.NetTcpBinding_IProfilerCommunication_TrackAssembly.params,
                    NetTcpBinding_IProfilerCommunication_TrackAssemblyOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for NetTcpBinding_IProfilerCommunication_TrackAssembly
            },  // NetTcpBinding_IProfilerCommunication_TrackAssembly
            { // NetTcpBinding_IProfilerCommunication_Stopping
                {    // operation description for NetTcpBinding_IProfilerCommunication_Stopping
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&opencover_profiler_wsdl.messages.IProfilerCommunication_Stopping_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&opencover_profiler_wsdl.messages.IProfilerCommunication_Stopping_OutputMessage, 
                    0,
                    0,
                    0,
                    0,
                    NetTcpBinding_IProfilerCommunication_StoppingOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for NetTcpBinding_IProfilerCommunication_Stopping
            },  // NetTcpBinding_IProfilerCommunication_Stopping
            {    // array of operations for NetTcpBinding_IProfilerCommunication
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.NetTcpBinding_IProfilerCommunication_Started.NetTcpBinding_IProfilerCommunication_Started,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.NetTcpBinding_IProfilerCommunication_TrackAssembly.NetTcpBinding_IProfilerCommunication_TrackAssembly,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.NetTcpBinding_IProfilerCommunication_Stopping.NetTcpBinding_IProfilerCommunication_Stopping,
            },    // array of operations for NetTcpBinding_IProfilerCommunication
            {    // contract description for NetTcpBinding_IProfilerCommunication
            3,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.operations,
            },  // end of contract description for NetTcpBinding_IProfilerCommunication
        },    // NetTcpBinding_IProfilerCommunication
    }, //  end of contracts 
    {// policies
        {
            WS_ENCODING_XML_BINARY_SESSION_1,
            WS_ADDRESSING_VERSION_1_0,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.NetTcpBinding_IProfilerCommunication.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.NetTcpBinding_IProfilerCommunication.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.NetTcpBinding_IProfilerCommunication.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.NetTcpBinding_IProfilerCommunication.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.NetTcpBinding_IProfilerCommunication.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.NetTcpBinding_IProfilerCommunication.envelopeVersion),
                },
            },
        },   // end of NetTcpBinding_IProfilerCommunication,
    }, // policies
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("<wsa10:EndpointReference xmlns:wsa10=\"http://www.w3.org/2005/08/addressing\">\n        <wsa10:Address>net.tcp://localhost:8000/OpenCover.Profiler.Host</wsa10:Address>\n      </wsa10:EndpointReference>",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
        },  // end of xmlStrings
        
        {   // tempuri_org_wsdldictionary
        // 80dedf24-553b-4cef-bcf9-1605779dec13 
        { 0x80dedf24, 0x553b, 0x4cef, { 0xbc, 0xf9, 0x16,0x05, 0x77, 0x9d, 0xec, 0x13 } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        1,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions


// operation: NetTcpBinding_IProfilerCommunication_Started
HRESULT WINAPI NetTcpBinding_IProfilerCommunication_Started(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.NetTcpBinding_IProfilerCommunication_Started.NetTcpBinding_IProfilerCommunication_Started,
        0,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: NetTcpBinding_IProfilerCommunication_TrackAssembly
HRESULT WINAPI NetTcpBinding_IProfilerCommunication_TrackAssembly(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in_opt __nullterminated WCHAR* moduleName, 
    __in_opt __nullterminated WCHAR* assemblyName, 
    __out BOOL* TrackAssemblyResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &moduleName;
    _argList[1] = &assemblyName;
    _argList[2] = &TrackAssemblyResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.NetTcpBinding_IProfilerCommunication_TrackAssembly.NetTcpBinding_IProfilerCommunication_TrackAssembly,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: NetTcpBinding_IProfilerCommunication_Stopping
HRESULT WINAPI NetTcpBinding_IProfilerCommunication_Stopping(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.NetTcpBinding_IProfilerCommunication_Stopping.NetTcpBinding_IProfilerCommunication_Stopping,
        0,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {// contracts
        {   // NetTcpBinding_IProfilerCommunication
            3,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.NetTcpBinding_IProfilerCommunication.operations,
        },    // end of NetTcpBinding_IProfilerCommunication
    }, // contracts
    { // policies
        {  // template description for NetTcpBinding_IProfilerCommunication
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.NetTcpBinding_IProfilerCommunication.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
    { // endpointReferences
        { // NetTcpBinding_IProfilerCommunication
            { // endpointAddressDescription
                WS_ADDRESSING_VERSION_1_0,
            },
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.NetTcpBinding_IProfilerCommunicationendpointReferenceString, // <wsa10:EndpointReference xmlns:wsa10="http://www.w3.org/2005/08/addressing">...
        },  // endof NetTcpBinding_IProfilerCommunication
    },  // endof endpointReferences 
}; // end of _tempuri_org_wsdl

HRESULT NetTcpBinding_IProfilerCommunication_CreateServiceProxy(
    __in_opt WS_TCP_BINDING_TEMPLATE* templateValue,
    __in_ecount_opt(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    __in const ULONG proxyPropertyCount,
    __deref_out_opt WS_SERVICE_PROXY** _serviceProxy,
    __in_opt WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_DUPLEX_SESSION,
        proxyProperties,
        proxyPropertyCount,
        WS_TCP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_TCP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.NetTcpBinding_IProfilerCommunication,
        sizeof(tempuri_org_wsdl.policies.NetTcpBinding_IProfilerCommunication),
        _serviceProxy,
        error);
}

HRESULT NetTcpBinding_IProfilerCommunication_CreateServiceEndpoint(
    __in_opt WS_TCP_BINDING_TEMPLATE* templateValue,
    __in_opt CONST WS_STRING* address,
    __in_opt struct NetTcpBinding_IProfilerCommunicationFunctionTable* functionTable,
    __in_opt WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    __in_ecount_opt(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    __in const ULONG endpointPropertyCount,
    __in WS_HEAP* heap,
    __deref_out_opt WS_SERVICE_ENDPOINT** serviceEndpoint,
    __in_opt WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.NetTcpBinding_IProfilerCommunication;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_DUPLEX_SESSION,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_TCP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_TCP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.NetTcpBinding_IProfilerCommunication,
        sizeof(tempuri_org_wsdl.policies.NetTcpBinding_IProfilerCommunication),
        serviceEndpoint,
        error);
}
